"""
PDF Report Generator
Converts analysis data into a professionally styled PDF report.
Uses fpdf2 — no external dependencies beyond what's already installed.
"""

from fpdf import FPDF, XPos, YPos
from datetime import datetime
from typing import Optional
import re


# ── Color Palette ──────────────────────────────────────────────────────────────
TEAL        = (20, 184, 166)
DARK_NAVY   = (15, 23, 42)
NAVY        = (30, 58, 95)
WHITE       = (255, 255, 255)
LIGHT_GRAY  = (245, 247, 250)
MID_GRAY    = (156, 163, 175)
DARK_GRAY   = (55, 65, 81)
TEXT        = (30, 30, 40)

SEV_COLORS  = {
    "high":   (239, 68,  68),
    "medium": (245, 158, 11),
    "low":    (16,  185, 129),
}
PRIO_COLORS = {
    "high":   (239, 68,  68),
    "medium": (245, 158, 11),
    "low":    (16,  185, 129),
}


def _clean(text: str) -> str:
    # Strip markdown and sanitize text for FPDF latin-1 rendering.
    if not text:
        return ""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.+?)\*",     r"\1", text)   # italic
    text = re.sub(r"#+\s*",          "",    text)   # headings
    text = re.sub(r"`(.+?)`",        r"\1", text)   # code
    # Smart quotes → straight
    text = text.replace("'", "'").replace("'", "'")
    text = text.replace(""", '"').replace(""", '"')
    # Dashes
    text = text.replace("—", "-").replace("–", "-")
    # Other common unicode
    text = text.replace("•", "*").replace("…", "...")
    text = text.replace(" ", " ").replace("™", "TM")
    text = text.replace("®", "(R)").replace("©", "(C)")
    # Final safety: drop any remaining non-latin-1 characters
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text.strip()


class TaxMindPDF(FPDF):
    """Custom FPDF subclass with TaxMind branding."""

    def __init__(self, client_name: str, entity_type: str, analysis_year: int):
        super().__init__()
        self.client_name   = client_name
        self.entity_type   = entity_type
        self.analysis_year = analysis_year
        self.set_auto_page_break(auto=True, margin=20)
        self.add_page()

    # ── Header / Footer ────────────────────────────────────────────────────────

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has no running header
        # Teal top bar
        self.set_fill_color(*TEAL)
        self.rect(0, 0, 210, 6, "F")
        self.set_y(10)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*MID_GRAY)
        self.cell(0, 5, f"TaxMind AI  |  {self.client_name}  |  {self.entity_type}  |  {self.analysis_year} Review", align="L")
        self.ln(6)

    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-14)
        self.set_fill_color(*LIGHT_GRAY)
        self.rect(0, self.get_y(), 210, 14, "F")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*MID_GRAY)
        self.cell(0, 10,
                  f"Confidential | {self.client_name} | Generated by TaxMind AI on {datetime.now().strftime('%B %d, %Y')}    Page {self.page_no()}",
                  align="C")

    # ── Helpers ────────────────────────────────────────────────────────────────

    def section_title(self, title: str, icon: str = ""):
        self.ln(4)
        # Left accent bar
        self.set_fill_color(*TEAL)
        self.rect(14, self.get_y(), 3, 9, "F")
        self.set_x(20)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*NAVY)
        self.cell(0, 9, _clean(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(3)

    def sub_title(self, text: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*DARK_GRAY)
        self.cell(0, 7, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def body_text(self, text: str, color=TEXT):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, _clean(text))
        self.ln(2)

    def kv_row(self, label: str, value: str, bg=LIGHT_GRAY):
        self.set_fill_color(*bg)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*DARK_GRAY)
        self.cell(55, 7, label, fill=True, border=0)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*TEXT)
        self.cell(0, 7, value, fill=False, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def divider(self):
        self.ln(3)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.4)
        self.line(14, self.get_y(), 196, self.get_y())
        self.ln(4)

    def badge(self, text: str, color: tuple, x: float, y: float, w: float = 22):
        r, g, b = color
        self.set_fill_color(r, g, b)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 7)
        self.set_xy(x, y)
        self.cell(w, 5, text.upper(), fill=True, align="C")
        self.set_text_color(*TEXT)


# ── Cover Page ─────────────────────────────────────────────────────────────────

def _cover_page(pdf: TaxMindPDF, priority_level: str, one_line_summary: str):
    # Dark navy background top half
    pdf.set_fill_color(*DARK_NAVY)
    pdf.rect(0, 0, 210, 110, "F")

    # Teal accent strip
    pdf.set_fill_color(*TEAL)
    pdf.rect(0, 108, 210, 4, "F")

    # TaxMind AI wordmark
    pdf.set_y(28)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 14, "TaxMind AI", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 8, "Client Financial Review Report", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Client info box
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 10, pdf.client_name, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*MID_GRAY)
    pdf.cell(0, 7,
             f"{pdf.entity_type}  |  Tax Year {pdf.analysis_year - 1} vs {pdf.analysis_year}",
             align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Priority badge (centered)
    prio_color = {"urgent": (239, 68, 68), "review": (245, 158, 11), "on-track": (16, 185, 129)}.get(priority_level, TEAL)
    prio_label = {"urgent": "URGENT - IMMEDIATE ACTION REQUIRED",
                  "review": "REVIEW - NEEDS ATTENTION",
                  "on-track": "ON TRACK - HEALTHY FINANCIALS"}.get(priority_level, priority_level.upper())
    badge_w = 90
    badge_x = (210 - badge_w) / 2
    pdf.ln(6)
    pdf.set_fill_color(*prio_color)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_x(badge_x)
    pdf.cell(badge_w, 7, prio_label, fill=True, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Summary line
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(*MID_GRAY)
    pdf.multi_cell(0, 6, _clean(str(one_line_summary)), align="C")

    # White area for meta info
    pdf.set_y(124)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK_GRAY)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*MID_GRAY)
    pdf.cell(0, 5, "CONFIDENTIAL - For authorized recipients only. Not for distribution.", align="C")

    # Page 2 starts fresh
    pdf.add_page()


# ── Section Builders ───────────────────────────────────────────────────────────

def _section_overview(pdf: TaxMindPDF, comparison_data: dict, summary: str):
    pdf.section_title("Financial Performance Overview")
    if summary:
        pdf.body_text(summary)

    rev  = comparison_data.get("revenue_comparison", {})
    gp   = comparison_data.get("gross_profit_comparison", {})
    ni   = comparison_data.get("net_income_comparison", {})
    health = comparison_data.get("overall_health", "N/A")

    # KV table
    rows = [
        ("Metric",                       f"Prior Year ({pdf.analysis_year - 1})",   f"Current Year ({pdf.analysis_year})",  "Change"),
        ("Revenue",                      f"${rev.get('prior', 0):,.0f}",             f"${rev.get('current', 0):,.0f}",       f"{rev.get('change_pct', 0):+.1f}%"),
        ("Gross Profit",                 f"${gp.get('prior', 0):,.0f}",              f"${gp.get('current', 0):,.0f}",        f"{gp.get('change_pct', 0):+.1f}%"),
        ("Net Income",                   f"${ni.get('prior', 0):,.0f}",              f"${ni.get('current', 0):,.0f}",        f"{ni.get('change_pct', 0):+.1f}%"),
        ("Overall Health",               "",                                          health.capitalize(),                     ""),
    ]

    col_w = [55, 38, 40, 35]
    for i, row in enumerate(rows):
        bg = NAVY if i == 0 else (LIGHT_GRAY if i % 2 == 0 else WHITE)
        txt_color = WHITE if i == 0 else TEXT
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*txt_color)
        pdf.set_font("Helvetica", "B" if i == 0 else "", 9)
        for j, cell in enumerate(row):
            pdf.cell(col_w[j], 7, str(cell), fill=True, border=0)
        pdf.ln()

    pdf.ln(4)

    # Key observations
    observations = comparison_data.get("key_observations", [])
    if observations:
        pdf.sub_title("Key Observations")
        for obs in observations:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*TEXT)
            pdf.set_x(17)
            pdf.cell(4, 6, "-")
            pdf.multi_cell(0, 6, _clean(obs))

    # Expense breakdown
    expenses = comparison_data.get("expense_categories", [])
    notable = [e for e in expenses if e.get("notable")]
    if notable:
        pdf.ln(3)
        pdf.sub_title("Notable Expense Changes")
        exp_cols = [70, 35, 35, 30]
        headers  = ["Category", "Prior Year", "Current Year", "Change %"]
        pdf.set_fill_color(*NAVY)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 9)
        for h, w in zip(headers, exp_cols):
            pdf.cell(w, 7, h, fill=True)
        pdf.ln()
        for i, exp in enumerate(notable[:8]):
            bg = LIGHT_GRAY if i % 2 == 0 else WHITE
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*TEXT)
            pdf.set_font("Helvetica", "", 9)
            chg = exp.get("change_pct", 0)
            chg_color = (239, 68, 68) if abs(chg) > 50 else TEXT
            pdf.cell(exp_cols[0], 6, str(exp.get("category", ""))[:35], fill=True)
            pdf.cell(exp_cols[1], 6, f"${exp.get('prior', 0):,.0f}", fill=True)
            pdf.cell(exp_cols[2], 6, f"${exp.get('current', 0):,.0f}", fill=True)
            pdf.set_text_color(*chg_color)
            pdf.cell(exp_cols[3], 6, f"{chg:+.1f}%", fill=True)
            pdf.set_text_color(*TEXT)
            pdf.ln()
    pdf.ln(2)


def _section_red_flags(pdf: TaxMindPDF, red_flags: list):
    pdf.divider()
    pdf.section_title("Areas of Concern - Red Flags")

    if not red_flags:
        pdf.set_fill_color(16, 185, 129)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 10, "  No significant issues found - financials look healthy.", fill=True,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        return

    # Sort: high -> medium -> low
    sev_order = {"high": 0, "medium": 1, "low": 2}
    sorted_flags = sorted(red_flags, key=lambda f: sev_order.get(f.get("severity", "low"), 2))

    for flag in sorted_flags:
        sev   = flag.get("severity", "low")
        color = SEV_COLORS.get(sev, TEAL)
        title = _clean(flag.get("title", ""))
        desc  = _clean(flag.get("description", ""))
        rec   = _clean(flag.get("recommendation", ""))

        # ── Title bar: colored background, white text, severity badge on right ──
        pdf.set_fill_color(*color)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_x(14)
        # Title takes most of the width, badge is a fixed cell on right
        pdf.cell(152, 7, f"  {title[:70]}", fill=True)
        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(30, 7, sev.upper(), fill=True, align="C",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # ── IRS Risk row (optional) ───────────────────────────────────────────
        if flag.get("irs_risk"):
            pdf.set_fill_color(254, 226, 226)
            pdf.set_text_color(185, 28, 28)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_x(14)
            pdf.cell(182, 6, "  IRS RISK - Requires immediate review and documentation",
                     fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # ── Description (light gray, flowing multi_cell) ──────────────────────
        if desc:
            pdf.set_fill_color(*LIGHT_GRAY)
            pdf.set_text_color(*DARK_GRAY)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(14)
            pdf.multi_cell(182, 5, desc, fill=True)

        # ── Recommendation (very light teal tint, flowing) ────────────────────
        if rec:
            pdf.set_fill_color(236, 253, 245)
            pdf.set_text_color(6, 95, 70)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_x(14)
            pdf.multi_cell(182, 5, f"Recommendation: {rec}", fill=True)

        pdf.ln(3)  # gap between cards


def _section_tax_plan(pdf: TaxMindPDF, tax_opportunities: list):
    pdf.divider()
    pdf.section_title("Tax Planning Recommendations")

    if not tax_opportunities:
        pdf.body_text("No tax planning opportunities identified at this time.")
        return

    for i, opp in enumerate(tax_opportunities):
        priority = opp.get("priority", "low")
        p_color  = PRIO_COLORS.get(priority, TEAL)
        savings  = opp.get("estimated_savings", 0)
        title    = _clean(opp.get("opportunity", ""))
        desc     = _clean(opp.get("description", ""))
        action   = _clean(opp.get("action_required", ""))
        deadline = _clean(opp.get("deadline", ""))

        # ── Header row: numbered teal chip + title + savings ─────────────────
        savings_str = f"  ~${savings:,.0f} savings" if savings > 0 else ""
        header_text = f"{i + 1}.  {title[:60]}"

        pdf.set_fill_color(*TEAL)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_x(14)
        # Title cell (left)
        pdf.cell(148, 7, header_text, fill=True)
        # Savings cell (right, green)
        pdf.set_fill_color(16, 185, 129)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(34, 7, savings_str, fill=True, align="C",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # ── Description (light gray, flowing) ─────────────────────────────────
        if desc:
            pdf.set_fill_color(*LIGHT_GRAY)
            pdf.set_text_color(*DARK_GRAY)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(14)
            pdf.multi_cell(182, 5, desc, fill=True)

        # ── Action row ────────────────────────────────────────────────────────
        if action:
            pdf.set_fill_color(236, 253, 245)
            pdf.set_text_color(6, 95, 70)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_x(14)
            pdf.multi_cell(182, 5, f"Action: {action}", fill=True)

        # ── Deadline row ──────────────────────────────────────────────────────
        if deadline:
            pdf.set_fill_color(255, 251, 235)
            pdf.set_text_color(120, 53, 15)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_x(14)
            pdf.cell(182, 5, f"Deadline: {deadline}", fill=True,
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.ln(4)


def _section_questions(pdf: TaxMindPDF, smart_questions: list):
    pdf.divider()
    pdf.section_title("Questions for Client Meeting")

    if not smart_questions:
        pdf.body_text("No smart questions generated.")
        return

    for i, q in enumerate(smart_questions):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*TEAL)
        pdf.set_x(14)
        pdf.cell(8, 6, f"{i + 1}.")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT)
        pdf.multi_cell(0, 6, _clean(q))
        pdf.ln(2)


def _section_next_steps(pdf: TaxMindPDF, priority_level: str, red_flags: list):
    pdf.divider()
    pdf.section_title("Next Steps & Timeline")

    steps_map = {
        "urgent": [
            ("Immediately", "Schedule emergency client meeting to discuss high-priority findings"),
            ("Within 1 week", "Address all IRS compliance issues identified in the red flags"),
            ("Within 2 weeks", "Implement top tax planning recommendations before year-end"),
            ("Within 1 month", "File any amended returns or make estimated tax payments as needed"),
        ],
        "review": [
            ("Within 2 weeks", "Schedule a client review meeting to walk through flagged items"),
            ("Within 1 month", "Gather supporting documentation for anomalous expense categories"),
            ("Before year-end", "Execute recommended tax planning strategies"),
            ("Next quarter", "Re-run analysis after implementing changes to verify improvement"),
        ],
        "on-track": [
            ("This month", "Share this report with the client as a positive performance review"),
            ("Before year-end", "Review tax planning opportunities and implement high-priority items"),
            ("Next quarter", "Schedule routine check-in - no urgent action required"),
            ("Annually", "Repeat full analysis after next tax return is filed"),
        ],
    }

    steps = steps_map.get(priority_level, steps_map["review"])
    col_w = [40, 140]
    for i, (timing, action) in enumerate(steps):
        bg = LIGHT_GRAY if i % 2 == 0 else WHITE
        pdf.set_fill_color(*bg)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*TEAL)
        pdf.cell(col_w[0], 7, _clean(timing), fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT)
        pdf.cell(col_w[1], 7, _clean(action), fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)
    # Disclaimer
    pdf.set_fill_color(*LIGHT_GRAY)
    pdf.set_fill_color(254, 243, 199)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(146, 64, 14)
    pdf.multi_cell(0, 5,
        "Disclaimer: This report is generated by TaxMind AI and is intended as a professional "
        "reference tool for licensed CPAs and tax professionals. It does not constitute legal or "
        "tax advice. All recommendations should be reviewed and verified by a qualified professional "
        "before implementation.")


# ── Main Public Function ───────────────────────────────────────────────────────

def generate_pdf_report(
    client_name: str,
    entity_type: str,
    analysis_year: int,
    priority_level: str,
    one_line_summary: str,
    comparison_data: dict,
    red_flags: list,
    tax_opportunities: list,
    smart_questions: list,
) -> bytes:
    """
    Generate a complete PDF report and return it as bytes.

    Args:
        client_name:       Client's business name
        entity_type:       S-Corp | LLC | Sole-Prop | Partnership
        analysis_year:     Current review year (e.g. 2024)
        priority_level:    urgent | review | on-track
        one_line_summary:  Short AI-generated summary
        comparison_data:   Dict from financial comparator agent
        red_flags:         List of dicts from anomaly detector
        tax_opportunities: List of dicts from tax planner
        smart_questions:   List of strings from tax planner

    Returns:
        PDF as bytes — ready to stream as application/pdf
    """
    pdf = TaxMindPDF(client_name, entity_type, analysis_year)

    _cover_page(pdf, priority_level, one_line_summary)
    _section_overview(pdf, comparison_data or {}, one_line_summary)
    _section_red_flags(pdf, red_flags or [])
    _section_tax_plan(pdf, tax_opportunities or [])
    _section_questions(pdf, smart_questions or [])
    _section_next_steps(pdf, priority_level, red_flags or [])

    return bytes(pdf.output())
